---
- hosts: all
  become: true
  strategy: free
  gather_facts: true
  vars:
    policy_name: all
  roles:
    - scap_client
  tasks:
    - name: "Run SCAP Scan"
      ansible.builtin.shell: "/usr/bin/foreman_scap_client {{ policy.id }}"
...
